### PR TITLE
Labels list view

### PR DESCRIPTION
**Pull request by allibragi**
Modified the createTextDiv function to add a label list in the main list view, under the link of the saved item.
Label have a style with background color set to the same color choose in Omnivore.
With one or more label the item height is slightly bigger, I left the item's image top aligned.

### CODE REVIEW

**Comment by herrherrmann** [comment]
Hey there, thanks a lot! I’m a bit busy nowadays, so it might take a few days until I can check this out. Please bear with me!

And I did notice that the `package-lock.json` has a lot of changes, even though there’s no change to the dependencies (in `package.json`). Perhaps you were installing dependencies with a Node/npm version that’s different from the one defined in `.nvmrc`? Either way, the changes in `package-lock.json` should probably be reverted back to the state from the `main` branch.

**Comment by allibragi** [comment]
No worries!

I've make some changes from a different PC, I think it could have a different version of node.
I've reverted the file to your last commit.

**Comment by herrherrmann** [comment]
Hey, I rewrote this a bit today! The labels are now wrapping and (just like in Omnivore itself) we should be using dots for the label color. Otherwise, the text might be very unreadable (if the label color is too close to the text color).

Here’s an example of how it looks now:

Bildschirmfoto 2023-10-20 um 17 02 30

If you’re fine with this, I’d merge this and release it soon!

**Comment by allibragi** [comment]
Hi, the changes are ok for me.
Thanks!

**Pull request merged**
